Bugfixes from latest feedbacks
carecon/openhab2-addons pull request #7
Opened 2017-04-18 20:00 UTC by dimalo

Hi Patrick, alles klar in Japan?
Heute mal in Deutsch, hörst du ja seltener die Tage 😄 🇩🇪 
folgende Änderungen im Detail:
* Ich hatte bereits die Abhängigkeiten im Manifest auf 1.8 angehoben, aber es war immernoch 1.7 im classpath referenziert -> fix
* Ein paar Lizenzen aktualisiert
* Plug liefert seine Stats im Heartbeat, dafür habe ich die Struktur der abstrakten Klassen vervollständigt und entsprechend das Parsing im Plug hinzugefügt. Das Gateway habe ich grad gecheckt, nach der Änderung kommen Heartbeats durch und werden sauber eingelesen, sollte also laufen
* Fürs Gateway muss nicht zwingend ein Volume Item definiert sein, nun wird immer 50% volume eingestellt statt einer Null Referenz 👍 
* Entdeckt: nur zwei User haben komischerweise diesen Fehler -> AbstractDiscoveryService stoppt alle scans beim startScan(), das führte zu einer Null Referenz, wenn der Socket anfangs garnicht initialisiert war

2017-04-19 03:54 UTC, pboos commented on addons/binding/org.openhab.binding.mihome/src/main/java/org/openhab/binding/mihome/handler/XiaomiActorPlugHandler.java
> +    void parseHeartbeat(JsonObject data) {
looking at the file, i see that this is duplicate code. and power_voltage is actually missing in parseHeartbeat. So maybe parseHeartbeat should just call parseReport. Or add the power_voltage part to parseHeartbeat and call it from parseReport. :)

2017-04-19 03:59 UTC, pboos commented on addons/binding/org.openhab.binding.mihome/src/main/java/org/openhab/binding/mihome/handler/XiaomiDeviceBaseHandler.java
> +        } else if (command.equals("read_ack") || command.equals("write_ack")) {
in XiaomiSensorBaseHandler and XiaomiActorGatewayHandler you seem to overwrite parseCommand to be able to parse read_ack and write_ack as parseHeartbeat. Maybe in here we should have them separate as well and call an abstract function parseReadAck or parseWriteAck. Then have XiaomiActorBaseHandler implement default functions for them. Or you can in here add them as just empty methods that are not abstract.
Does that make sense or is there a reason to better have it this way?

2017-04-19 04:00 UTC, pboos commented on addons/binding/org.openhab.binding.mihome/src/main/java/org/openhab/binding/mihome/handler/XiaomiDeviceBaseHandler.java
> +        } else if (command.equals("read_ack") || command.equals("write_ack")) {
In XiaomiSensorBaseHandler: we then could just call ```parseHeartbeat()``` from within ```parseReadAck()```
And in XiaomiActorGatewayHandler: we then could just call ```parseHeartbeat()``` from within ```parseReadAck()``` and ```parseWriteAck()```

2017-04-19 04:03 UTC, pboos commented
Ja stimmt, deutsch höre ich nicht so oft :D. Nur mit den Kindern zu Hause jeweils Deutsch :).
Pull request sieht gut aus, bis auf ein paar Sachen. Diese sind nicht kritisch, aber wäre ev. schön diese zu bereinigen, wenn du gleicher Meinung. Das bereinigen sollte eh nur ein paar Minuten dauern denke ich ;-)

2017-04-19 17:55 UTC, dimalo commented on addons/binding/org.openhab.binding.mihome/src/main/java/org/openhab/binding/mihome/handler/XiaomiActorPlugHandler.java
> +    void parseHeartbeat(JsonObject data) {
some user posted a log:

23:03:59.557 [DEBUG] [g.mihome.handler.XiaomiBridgeHandler] - Received message {"cmd":"heartbeat","model":"plug","sid":"158d00013e2884","short_id":15645,"data":"{"voltage":3600,"status":"on","inuse":"1","power_consumed":"31943","load_power":"90"}"}
23:03:59.557 [DEBUG] [ihome.handler.XiaomiActorPlugHandler] - Item got update: {"cmd":"heartbeat","model":"plug","sid":"158d00013e2884","short_id":15645,"data":"{"voltage":3600,"status":"on","inuse":"1","power_consumed":"31943","load_power":"90"}"}
23:04:17.266 [DEBUG] [g.mihome.handler.XiaomiBridgeHandler] - Received message {"cmd":"heartbeat","model":"plug","sid":"158d00010ec5bd","short_id":41076,"data":"{"voltage":3600,"status":"off","inuse":"0","power_consumed":"54351","load_power":"0"}"}
23:04:17.266 [DEBUG] [ihome.handler.XiaomiActorPlugHandler] - Item got update: {"cmd":"heartbeat","model":"plug","sid":"158d00010ec5bd","short_id":41076,"data":"{"voltage":3600,"status":"off","inuse":"0","power_consumed":"54351","load_power":"0"}"}

It differs from the chinese api description. copied the parts I could see, but actually you're right...

2017-04-20 00:32 UTC, pboos requested changes
Versuche hier mal mit "Review" feature von github. Noch nie benutzt bisher :). Also nur noch etwas kleines glaube ich. Was denkst du dazu? Stimmt was ich sage oder sehe ich es falsch?

2017-04-20 00:32 UTC, pboos commented on addons/binding/org.openhab.binding.mihome/src/main/java/org/openhab/binding/mihome/handler/XiaomiActorGatewayHandler.java
> +        if (command.equals("report")) {
Because of the added readAck and writeAck methods, this override is probably not required anymore, right?

2017-04-20 08:07 UTC, pboos approved these changes

2017-04-20 08:09 UTC, merged